version: '3.9'

services:
    php:
        platform: linux/x86_64
        container_name: ms-shared-php
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/srv/app:rw,cached
            - ./docker/php-fpm/.ssh:/root/.ssh:rw,cached
        ports:
            - "9000:9000"
            - "8000:8000"

    mysql:
        image: mysql:5.7
        platform: linux/amd64
        container_name: ms-shared-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DB:-app}
            MYSQL_USER: ${MYSQL_USER:-symfony}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
        ports:
            - '3306:3306'
        volumes:
            - symfony_ms_shared_mysql:/var/lib/mysql:rw,cached

    nginx:
        image: nginx:stable-alpine
        platform: linux/x86_64
        container_name: ms-shared-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./public:/srv/app/public
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/ssl/localhost.key:/etc/ssl/localhost.key
            - ./docker/nginx/ssl/localhost.crt:/etc/ssl/localhost.crt
        depends_on:
            - php
            - mysql

    mailer:
        image: schickling/mailcatcher
        container_name: ms-shared-mailer
        platform: linux/x86_64
        ports:
            - "51025:1025"
            - "51080:1080"

volumes:
    symfony_ms_shared_mysql:
