apps:
    demo:
        enabled: true
        repository: 'git@bitbucket.org:3pixelsmedia/ms-demo.git'
        requires: [ 'security' ]
    security:
        enabled: true
        repository: 'git@bitbucket.org:3pixelsmedia/ms-security.git'
        requires: []
