apps:
    demo:
        enabled: true
        repository: 'git@github.com:coral-media/ms-demo.git'
        requires: [security]
        namespace: MsDemo
    security:
        enabled: true
        repository: 'git@github.com:coral-media/ms-security.git'
        requires: {  }
        namespace: MsSecurity
